TYPO3:
  Flow:
    i18n:
      defaultLocale: 'da'
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'print'
          title: 'Print'
          position: 200
